# Copyright

I'm not the author of these data tables.

For this project, the data are obtained from the official URL of the government of México whose author is “Dirección General de Epidemiología”:


__Corona Virus Data:__ https://www.gob.mx/salud/documentos/datos-abiertos-152127

__Data Dictionary:__ https://www.gob.mx/salud/documentos/datos-abiertos-152127



---------------------------


__My principal objective is apply my knowledge like Data Scientist on these data to generate useful results.__

Data dictionary for better understanding:

----

| Nº | NOMBRE DE VARIABLE  | DESCRIPCIÓN DE VARIABLE|
|----|---------------------|------------------------|
| 1  | FECHA_ACTUALIZACION | Update date.|
| 2  | ID_REGISTRO         | Case Number ID.|
| 3  | ORIGEN              | It specifies if patient is being monitored by USMER (Healthcare Monitoring Unit for Respiratory Diseases) or not. |
| 4  | SECTOR              | It identifies the type of National Health System institution that provided the care.|
| 5  | ENTIDAD_UM          | Identifies the entity where the medical unit that provided the care is located.|
| 6  | SEXO                | Sex.|
| 7  | ENTIDAD_NAC         | Patient's birth place.|
| 8  | ENTIDAD_RES         | Entity of residence of the patient.|
| 9  | MUNICIPIO_RES       | Patient's neighborhood of residence.|
| 10 | TIPO_PACIENTE       | It identifies the type of care the patient received in the unit. It is called outpatient if returned home or inpatient if admitted to hospital.|
| 11 | FECHA_INGRESO       | Patient's date of admission to the care unit.|
| 12 | FECHA_SINTOMAS      | Symptom date.|
| 13 | FECHA_DEF           | Date of death.|
| 14 | INTUBADO            | Tracheal intubation.|
| 15 | NEUMONIA            | Pneumonia.|
| 16 | EDAD                | Age.|
| 17 | NACIONALIDAD        | Mexican or foreign.|
| 18 | EMBARAZO            | Pregnancy.|
| 19 | HABLA_LENGUA_INDIG  | Indigenous Langauge.|
| 20 | DIABETES            | Diabetes.|
| 21 | EPOC                | EPOC.|
| 22 | ASMA                | Asthma.|
| 23 | INMUSUPR            | Immunosuppression.|
| 24 | HIPERTENSION        | Hypertension.|
| 25 | OTRAS_COM           | Other diseases.|
| 26 | CARDIOVASCULAR      | Cardiovascular disease.|
| 27 | OBESIDAD            | Obesity.|
| 28 | RENAL_CRONICA       | Chronic kidney disease.|
| 29 | TABAQUISMO          | Smoking.|
| 30 | OTRO_CASO           | Identifies if the patient had contact with any other cases diagnosed with SARS CoV-2|
| 31 | RESULTADO           | Analysis result|
| 32 | MIGRANTE            | Migrant.|
| 33 | PAIS_NACIONALIDAD   | Nationality.|
| 34 | PAIS_ORIGEN         | Home state.|
| 35 | UCI                 | Identifies if the patient required admission to an Intensive Care Unit.|

In [1]:
import pandas as pd
import numpy as np
import urllib
import zipfile
import os 
import shutil
from datetime import datetime, timedelta

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',None)

# Data Cleaning and Formating

In [2]:
#Download the actual version of data
url = 'http://187.191.75.115/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip'
#Create a new folder to download the data
folder_path = 'DataCovidMx'
#to avoid duplicates when updating, it is necessary to remove the csv
if os.path.exists(folder_path):
    shutil.rmtree(folder_path)
    os.makedirs(folder_path)   
else:
    os.makedirs(folder_path)
#Download the file from URL
urllib.request.urlretrieve(url,"DataCovidMx/DataCovidCSV.zip")
#getting the file name
file_name = zipfile.ZipFile("DataCovidMx/DataCovidCSV.zip").namelist()
#extracting file
with zipfile.ZipFile("DataCovidMx/DataCovidCSV.zip", 'r') as zip_ref:
    zip_ref.extractall("DataCovidMx/")

In [3]:
#The original data contain accented characters (México), and others not recognized. 
#So, it's necessary to specify the encoding parameter in pandas as "unicode_escape"

df = pd.read_csv('DataCovidMx/'+ file_name[0], encoding= 'unicode_escape')
print(df.shape)
df.head()

(861852, 35)

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,FECHA_DEF,INTUBADO,NEUMONIA,EDAD,NACIONALIDAD,EMBARAZO,HABLA_LENGUA_INDIG,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-22,05ab01,2,3,27,2,27,27,4,1,2020-06-16,2020-06-06,9999-99-99,97,2,16,1,97,2,2,2,2,2,2,2,2,2,2,2,1,1,99,MÃ©xico,99,97
1,2020-07-22,08398c,2,3,27,2,27,27,4,1,2020-06-23,2020-06-14,9999-99-99,97,2,27,1,97,2,2,2,2,2,2,2,2,2,2,2,1,1,99,MÃ©xico,99,97
2,2020-07-22,174902,2,4,31,2,31,31,38,2,2020-04-17,2020-04-11,2020-04-21,2,1,56,1,97,2,2,2,2,2,1,2,2,1,2,2,99,1,99,MÃ©xico,99,2
3,2020-07-22,0d23c3,2,4,9,2,16,9,14,1,2020-04-24,2020-04-23,9999-99-99,97,2,30,1,97,2,2,2,2,2,2,1,2,2,2,2,99,1,99,MÃ©xico,99,97
4,2020-07-22,0c01fd,2,4,2,1,2,2,2,1,2020-04-24,2020-04-19,9999-99-99,97,2,32,1,2,2,2,2,2,2,2,2,2,1,2,2,99,1,99,MÃ©xico,99,97

## Replace the place ID by Place Name

The columns "ENTIDAD_RES" and "MUNICIPIO_RES" refer to the state and municipality of residence respectively. These are coded by numbers so that they can be replaced by their respective names. 

For make this I will use mexican states by ID table and the Data Dictionary.xlsx

In [4]:
#Define Mexican states table ID
state_table = pd.read_excel('Catalogo.xlsx', sheet_name='Catálogo de ENTIDADES')
state_table.drop(labels= 'ABREVIATURA', axis = 1, inplace = True)
state_table.rename(columns= {'CLAVE_ENTIDAD':'ID', 'ENTIDAD_FEDERATIVA':'State'},inplace= True)
state_table.head()

   ID                 State
0   1        AGUASCALIENTES
1   2       BAJA CALIFORNIA
2   3   BAJA CALIFORNIA SUR
3   4              CAMPECHE
4   5  COAHUILA DE ZARAGOZA

In [5]:
#Import Data Dictionary - Municipality ID by State ID
Id_state = pd.read_excel("Catalogo.xlsx", sheet_name='Catálogo MUNICIPIOS')

#Creating a new column that contains the Municipality ID by state ID
Id_state['Full_ID']= Id_state['CLAVE_ENTIDAD'].astype(str) + '-' + Id_state['CLAVE_MUNICIPIO'].astype(str)
Id_state.head()

   CLAVE_MUNICIPIO       MUNICIPIO  CLAVE_ENTIDAD Full_ID
0                1  AGUASCALIENTES              1     1-1
1                2        ASIENTOS              1     1-2
2                3        CALVILLO              1     1-3
3                4           COSÍO              1     1-4
4                5     JESÚS MARÍA              1     1-5

In [6]:
#Dictionary creation to replace the ID of the "ENTIDAD_RES" and "MUNICIPIO_RES" by name
dict_municipality = pd.Series(Id_state.MUNICIPIO.values, index = Id_state.Full_ID).to_dict()
dict_state = pd.Series(state_table.State.values, index= state_table.ID).to_dict()

For replace the ID by name it's neccesary create a new column in the original DataSet that contain the State ID and Municipality ID.

In [7]:
#Defie the new column
df['MUNICIPIO_RES'] = df['ENTIDAD_RES'].astype(str) + '-' + df['MUNICIPIO_RES'].astype(str)
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,FECHA_DEF,INTUBADO,NEUMONIA,EDAD,NACIONALIDAD,EMBARAZO,HABLA_LENGUA_INDIG,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-22,05ab01,2,3,27,2,27,27,27-4,1,2020-06-16,2020-06-06,9999-99-99,97,2,16,1,97,2,2,2,2,2,2,2,2,2,2,2,1,1,99,MÃ©xico,99,97
1,2020-07-22,08398c,2,3,27,2,27,27,27-4,1,2020-06-23,2020-06-14,9999-99-99,97,2,27,1,97,2,2,2,2,2,2,2,2,2,2,2,1,1,99,MÃ©xico,99,97
2,2020-07-22,174902,2,4,31,2,31,31,31-38,2,2020-04-17,2020-04-11,2020-04-21,2,1,56,1,97,2,2,2,2,2,1,2,2,1,2,2,99,1,99,MÃ©xico,99,2
3,2020-07-22,0d23c3,2,4,9,2,16,9,9-14,1,2020-04-24,2020-04-23,9999-99-99,97,2,30,1,97,2,2,2,2,2,2,1,2,2,2,2,99,1,99,MÃ©xico,99,97
4,2020-07-22,0c01fd,2,4,2,1,2,2,2-2,1,2020-04-24,2020-04-19,9999-99-99,97,2,32,1,2,2,2,2,2,2,2,2,2,1,2,2,99,1,99,MÃ©xico,99,97

In [8]:
#replace the code with the name
df['ENTIDAD_RES'].replace(dict_state,inplace = True)
df['MUNICIPIO_RES'].replace(dict_municipality,inplace = True)
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,FECHA_DEF,INTUBADO,NEUMONIA,EDAD,NACIONALIDAD,EMBARAZO,HABLA_LENGUA_INDIG,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-22,05ab01,2,3,27,2,27,TABASCO,CENTRO,1,2020-06-16,2020-06-06,9999-99-99,97,2,16,1,97,2,2,2,2,2,2,2,2,2,2,2,1,1,99,MÃ©xico,99,97
1,2020-07-22,08398c,2,3,27,2,27,TABASCO,CENTRO,1,2020-06-23,2020-06-14,9999-99-99,97,2,27,1,97,2,2,2,2,2,2,2,2,2,2,2,1,1,99,MÃ©xico,99,97
2,2020-07-22,174902,2,4,31,2,31,YUCATÁN,HUNUCMÁ,2,2020-04-17,2020-04-11,2020-04-21,2,1,56,1,97,2,2,2,2,2,1,2,2,1,2,2,99,1,99,MÃ©xico,99,2
3,2020-07-22,0d23c3,2,4,9,2,16,CIUDAD DE MÉXICO,BENITO JUÁREZ,1,2020-04-24,2020-04-23,9999-99-99,97,2,30,1,97,2,2,2,2,2,2,1,2,2,2,2,99,1,99,MÃ©xico,99,97
4,2020-07-22,0c01fd,2,4,2,1,2,BAJA CALIFORNIA,MEXICALI,1,2020-04-24,2020-04-19,9999-99-99,97,2,32,1,2,2,2,2,2,2,2,2,2,1,2,2,99,1,99,MÃ©xico,99,97

## Removing the negative cases and classify the dead cases

The next step is remove the negative cases and classify the dead cases. 

|Key	|Description|
|-------|-----------|
|1	|Positivo SARS-CoV-2|
|2	|No positivo SARS-CoV-2|
|3	|Resultado pendiente|

The data format of the column "FECHA_DEF" is specified as follows: 

|Format | Description|key|
|-------|------------|---|
|Year-month-day|Date of death|1|
|9999-99-99|Unassigned date|0|

The unassigned date means that the patien is not dead

In [9]:
#only keept positive cases
df.drop(df[df['RESULTADO'] == 2].index, inplace = True)
df.drop(df[df['RESULTADO'] == 3].index, inplace = True)
df['RESULTADO'].value_counts()

1    362274
Name: RESULTADO, dtype: int64

In [10]:
#clasify the death cases and non-death caes
df.loc[df.FECHA_DEF != '9999-99-99', 'FECHA_DEF'] = 1  #Pople death
df.loc[df.FECHA_DEF == '9999-99-99', 'FECHA_DEF'] = 0  #People alive
df['FECHA_DEF'].value_counts()

0    321084
1     41190
Name: FECHA_DEF, dtype: int64

## Formating the columns 

The format of the columns should be as follows:

+ Date Columns: Datetime

In [11]:
#Change the format of date columns
df['FECHA_ACTUALIZACION'] = pd.to_datetime(df['FECHA_ACTUALIZACION'])
df['FECHA_INGRESO'] = pd.to_datetime(df['FECHA_INGRESO'])
df['FECHA_SINTOMAS'] = pd.to_datetime(df['FECHA_SINTOMAS'])


print(df[["FECHA_ACTUALIZACION","FECHA_SINTOMAS","FECHA_SINTOMAS"]].dtypes)

FECHA_ACTUALIZACION    datetime64[ns]
FECHA_SINTOMAS         datetime64[ns]
FECHA_SINTOMAS         datetime64[ns]
dtype: object

# Exploratory data analysis

In order to drop the unnecessary columns, the analysis will reveal: 
+ Which are the columns that provide more information?
+ Which columns can be deleted?

To get a better understanding, the next table explains the keys that describe the most columns.

|key	|Descriptor|Apply|
|-------|----------|-----|
|1	|Yes|
|2	|No|
|97|Does not apply|Sector, Entidad_nac, intubado,Neumonia, Embarazo, Habla_lengua_indig, Diabetes, EPOC, Asma, Otra_Com, Cardiovascular,  Obesidad, Renasl_cronica, Tabaquismo, Otro_caso, Migrante and UCI|
|98	|Ignored|
|99 |Unspecified|

You can see that keys 2, 97, 98 and 99 are very similar, then they can be classified as NA.

In [12]:
#Create a function that highlight the values greater thant 97 equal to 2

def color_red(val):
    color = 'red' if val >= 97 and val < 100 or val == 2 else 'white'
    return 'color: %s' % color

In [13]:
less_significant_columns = df.describe().transpose().style.applymap(color_red)
less_significant_columns

As you can see, the columns referring to comorbidity do not provide relevant information as well as the columns that contain chronic conditions.

# Feature engineering and selection
 
In this section, based on the previous analysis, the columns that do not provide relevant information will be eliminated.

### Droped Columns 

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0lax">Columns dropped</th>
    <th class="tg-0lax">Reason</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">FECHA_ACTUALIZACION</td>
    <td class="tg-0lax">The update date are the same value in each row </td>
  </tr>
  <tr>
    <td class="tg-0lax">ID_REGISTRO</td>
    <td class="tg-0lax">This is a random case identifier</td>
  </tr>
  <tr>
    <td class="tg-0lax">ORIGEN</td>
    <td class="tg-0lax">Most cases are not monitored</td>
  </tr>
  <tr>
    <td class="tg-0lax">SECTOR</td>
    <td class="tg-0lax" rowspan="2">Both rows refer to where the health care facility provides care for the patient</td>
  </tr>
  <tr>
    <td class="tg-0lax">ENTIDAD_UM</td>
  </tr>
  <tr>
    <td class="tg-0lax">SEXO</td>
    <td class="tg-0lax">The virus does not differentiate gender</td>
  </tr>
  <tr>
    <td class="tg-0lax">TIPO_PACIENTE</td>
    <td class="tg-0lax">It only matters if the patient is infected or not</td>
  </tr>
  <tr>
    <td class="tg-0lax">ENTIDAD_NAC</td>
    <td class="tg-0lax">It's irrelevant where the patient was born.</td>
  </tr>
  <tr>
    <td class="tg-0lax">FECHA_INGRESO</td>
    <td class="tg-0lax">Specifies a date after the start of symptoms</td>
  </tr>
  <tr>
    <td class="tg-0lax">INTUBADO</td>
    <td class="tg-0lax">Most cases are not specified</td>
  </tr>
  <tr>
    <td class="tg-0lax">NEUMONIA</td>
    <td class="tg-0lax">Most cases are negative</td>
  </tr>
  <tr>
    <td class="tg-0lax">EDAD</td>
    <td class="tg-0lax">in order to make a temporal prediction of this data may or may not be irrelevant </td>
  </tr>
  <tr>
    <td class="tg-0lax">NACIONALIDAD</td>
    <td class="tg-0lax">Nationality is irrelevant since most people talk about Mexicans</td>
  </tr>
  <tr>
    <td class="tg-0lax">EMBARAZO</td>
    <td class="tg-0lax">Most of the data is not specified</td>
  </tr>
  <tr>
    <td class="tg-0lax">HABLA_LENGUA_INDIG</td>
    <td class="tg-0lax">Most of the data is not specified</td>
  </tr>
  <tr>
    <td class="tg-0lax">DIABETES</td>
    <td class="tg-0lax" rowspan="11">Most cases have no or no specified comorbidity</td>
  </tr>
  <tr>
    <td class="tg-0lax">EPOC</td>
  </tr>
  <tr>
    <td class="tg-0lax">ASMA</td>
  </tr>
  <tr>
    <td class="tg-0lax">INMUSUPR</td>
  </tr>
  <tr>
    <td class="tg-0lax">HIPERTENSION</td>
  </tr>
  <tr>
    <td class="tg-0lax">OTRAS_COM</td>
  </tr>
  <tr>
    <td class="tg-0lax">CARDIOVASCULAR</td>
  </tr>
  <tr>
    <td class="tg-0lax">OBESIDAD</td>
  </tr>
  <tr>
    <td class="tg-0lax">RENAL_CRONICA</td>
  </tr>
  <tr>
    <td class="tg-0lax">TABAQUISMO</td>
  </tr>
  <tr>
    <td class="tg-0lax">OTRO_CASO</td>
  </tr>
  <tr>
    <td class="tg-0lax">MIGRANTE</td>
    <td class="tg-0lax">Most of the data is not specified</td>
  </tr>
  <tr>
    <td class="tg-0lax">PAIS_NACIONALIDAD</td>
    <td class="tg-0lax">Most cases are from Mexico</td>
  </tr>
  <tr>
    <td class="tg-0lax">PAIS_ORIGEN</td>
    <td class="tg-0lax">Most of the data is not specified</td>
  </tr>
  <tr>
    <td class="tg-0lax">UCI</td>
    <td class="tg-0lax">Most of the data is not specified</td>
  </tr>
</tbody>
</table>

In [14]:
#Create a list whit unnecessary columns "Uc"
Uc = ['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM', 'SEXO', 'ENTIDAD_NAC', 'TIPO_PACIENTE', 'FECHA_INGRESO', 'INTUBADO', 'NEUMONIA', 'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
 'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM', 'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO', 'OTRO_CASO', 'MIGRANTE', 'PAIS_NACIONALIDAD', 'PAIS_ORIGEN', 'UCI']
#Drop irrelevant items
df.drop(Uc, axis=1, inplace=True)

#Rename columns
df.rename(columns={"ENTIDAD_RES":"State","MUNICIPIO_RES":"Municipality", "FECHA_SINTOMAS":"Date", "RESULTADO":"Confirmed", "FECHA_DEF":"Deaths"}, inplace= True)

In [15]:
df.head()

              State   Municipality       Date Deaths  Confirmed
0           TABASCO         CENTRO 2020-06-06      0          1
1           TABASCO         CENTRO 2020-06-14      0          1
2           YUCATÁN        HUNUCMÁ 2020-04-11      1          1
3  CIUDAD DE MÉXICO  BENITO JUÁREZ 2020-04-23      0          1
4   BAJA CALIFORNIA       MEXICALI 2020-04-19      0          1

In [16]:
df.sort_values(by=['Date'], inplace= True)
df.reset_index(drop=True, inplace=True)
df.head()

             State              Municipality       Date Deaths  Confirmed
0       NUEVO LEÓN  SAN NICOLÁS DE LOS GARZA 2020-01-13      0          1
1          SINALOA                  CULIACÁN 2020-01-29      0          1
2  BAJA CALIFORNIA                   TIJUANA 2020-02-06      0          1
3           MÉXICO       TLALNEPANTLA DE BAZ 2020-02-19      0          1
4           MÉXICO              HUIXQUILUCAN 2020-02-21      0          1

In [17]:
#Create an empty list for recover cases
list_recover = []
#Today variable
today = datetime.now().strftime("%Y/%m/%d")
today = datetime.strptime(today, "%Y/%m/%d")
    
#If the patient is not dead, check if it's been more than 15 days
for  date, death in zip(df['Date'],df['Deaths']): 
    if death == 0:
        day = (today - date).days
        if day > 15:
            recover=1
    else:
        recover=0
                
    list_recover.append(recover)
    
df['Recovered'] = list_recover

In [18]:
df['Recovered'].value_counts()

1    287635
0     74639
Name: Recovered, dtype: int64

In [19]:
list_active = []
#If the patient isn't recovered and isn't dead then is active
for recov, death in zip (df['Recovered'],df['Deaths']):
    if recov == 0 and death == 0:
        active = 1
    else:
        active = 0 
    list_active.append(active)

df['Active'] = list_active

In [20]:
Final=df.groupby(['State','Municipality','Date'])[['Deaths','Confirmed','Recovered','Active']].apply(lambda x: (x==1).sum()).reset_index()

In [21]:
Final.head()

,State,Municipality,Date,Deaths,Confirmed,Recovered,Active
0,AGUASCALIENTES,AGUASCALIENTES,2020-03-07,0,1,1,0
1,AGUASCALIENTES,AGUASCALIENTES,2020-03-10,0,1,1,0
2,AGUASCALIENTES,AGUASCALIENTES,2020-03-12,0,1,1,0
3,AGUASCALIENTES,AGUASCALIENTES,2020-03-14,0,1,1,0
4,AGUASCALIENTES,AGUASCALIENTES,2020-03-16,0,2,2,0

### Checking the integrity of the data

In [22]:
print("Recovered Cases: " ,Final['Recovered'].sum())
print("Death Cases: ",Final['Deaths'].sum())
print("Confirmed Cases: ",Final['Confirmed'].sum())
print("Active Cases: ",Final['Active'].sum())

Recovered Cases:  287635
Death Cases:  41190
Confirmed Cases:  362274
Active Cases:  33449

In [23]:
Check = np.setdiff1d(Final['Municipality'],Id_state['MUNICIPIO'])
Check.tolist()

['17-56', '17-63', '9-106']

In [25]:
for i in Check:
    index_to_remove = Final[(Final['Municipality'] == i)].index_to_remove
    Final.drop(index_to_remove,axis = 0, inplace = True)

AttributeError: 'DataFrame' object has no attribute 'tolist'

In [ ]:
Final.to_csv("Covid_19_Mexico_Clean_Complete.csv",index = False)